align_depth: false
border_px: 15
center_bias: 0.5
crop_size: 1024
dilate_pixel: 16
edge_sigma: 5.0
fov_map:
  atmosphere: 80.0
  ground_or_floor: 90.0
  sky_or_ceiling: 90.0
fovdeg: 90.0
ground_yaws:
- 0
- 90
- 180
- 270
guidance_scale: 7.0
horizontal_yaws:
- 45
- -45
- 135
- -135
- 90
- -90
in_out: outdoor
out_h: 2048
out_w: 4096
pitch_map:
  atmosphere: 0.0
  ground_or_floor: -45.0
  sky_or_ceiling: 45.0
sky_yaws:
- 0
- 90
- 180
- 270
steps: 1
