# config.yaml

out_w: 4096 
out_h: 2048

pitch_map:
  atmosphere:      0.0
  sky_or_ceiling:  60.0
  ground_or_floor: -60.0

horizontal_yaws: [30, -30, 150, -150, 60, -60, 120, -120]
sky_yaws:        [0, 90, 180, 270]
ground_yaws:     [0, 90, 180, 270]

fov_map:
  atmosphere:      80.0
  sky_or_ceiling:  100.0
  ground_or_floor: 100.0

guidance_scale: 7.0
steps:          50
dilate_pixel:   16

fovdeg:         90.0
border_px:      15

crop_size:      1024       
edge_sigma:     3.0        
center_bias:    1.0       
align_depth:    false      # optional scale alignment

in_out: "outdoor"
