# config.yaml
pitch_map:
  atmosphere:      0.0
  sky_or_ceiling:  45.0
  ground_or_floor: -45.0

horizontal_yaws: [45, -45, 135, -135, 90, -90]
sky_yaws:        [0, 90, 180, 270]
ground_yaws:     [0, 90, 180, 270]

fov_map:
  atmosphere:      75.0
  sky_or_ceiling:  100.0
  ground_or_floor: 100.0

guidance_scale: 7.0
steps:          50
dilate_pixel:   16

fovdeg:         90.0
border_px:      10

crop_size:      1024       
edge_sigma:     5.0        
center_bias:    0.5       
align_depth:    false      # optional scale alignment

in_out: "outdoor"
